#!/usr/bin/env bash
# This is a line of text
sudo apt -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt install -y haproxy=2.4.\*
sudo apt update -y && sudo apt upgrade -y
sudo sh -c 'echo "
frontend load_balancer
	bind *:80
	mode http
	default_backend webserver
backend webserver
	balance roundrobin
	mode http
	server 4403-web-01 54.234.239.181:80 check
	server 4403-web-02 3.90.239.54:80 check" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
