#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely
sudo bash -c "$BASHPID > /var/run/myscript.pid"
trap "echo I hate the kill command; sudo rm /var/run/myscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm /var/run/myscript.pid" SIGQUIT
while true
do
	echo "To infinity and beyond"
done
